--- 

- hosts: all
  become: yes
  tasks: 

  - name: install TMUX package
    yum:
      name: tmux  
      state: absent
    when: ansible_distribution == "CentOS"
    
  - name: install TMUX package
    apt:
      name: tmux
      state: absent
    when: ansible_distribution == "Ubuntu"
