---

- hosts: all
  become: true
  pre_tasks: 

  - name: install updates (CentOS)
    package:
      update_cache: yes
 

  - name: install updates (Ubuntu)
    package:
      update_cache: yes

- hosts: web_servers 
  become: true
  tasks:

  - name: install mariadb in "Ubuntu" 
    when: ansible_distribution =="Ubuntu"
    package:
     name:
        - mariadb-server
     state: absent 

  - name: install mariadb in "CentOS"
    when: ansible_distribution =="CentOS"
    package:
     name:
        - mariadb  
     state: absent 

- hosts: ftp_servers  
  become: true
  tasks:

  - name: install tmux in "Ubuntu"
    when: ansible_distribution =="Ubuntu"
    package:
     name:
        - tmux  
     state: absent 

  - name: install tmux in "CentOS"
    when: ansible_distribution =="CentOS"
    package:
     name:
        - tmux
     state: absent   
    
