---

- hosts: all
  become: sudo
  pre_tasks:
  tags: upadate

  - name: "upgrade all packages"
    package: name=* state=latest
    when: ansible_distribution == "CentOS"

  - name: "Updating Ubuntu"
    apt:
      update_cache: true
      upgrade: dist
    when: ansible_disribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: removing tmux in "Ubuntu" 
    tags: tmux,ubuntu,remove
    when: ansible_distribution =="Ubuntu"
    package:
     name:
        - tmux
     state: absent 

  - name: removing tmux in "CentOS"
    tags: tmux,centos,remove
    when: ansible_distribution =="CentOS"
    package:
     name:
        - tmux 
     state: absent 

- hosts: ftp_servers  
  become: true
  tasks:

  - name: install tmux in "Ubuntu"
    when: ansible_distribution =="Ubuntu"
    package:
     name:
        - tmux  
     state: absent 

  - name: install tmux in "CentOS"
    when: ansible_distribution =="CentOS"
    package:
     name:
        - tmux
     state: absent   
    
