--- 

- hosts: all
  tasks: 

  - name: Install tmux or apache2 for CentOS
    yum:
      name:
        
        - tmux  
        - httpd
      
      state: present
    
      when: ansible_distribution == "CentOS"
 
  - name: Install tmux or apache2 for Ubuntu
    apt:
      name: 
        - tmux
        - apache2
      state: present
    
      when: ansible_distribution == "Ubuntu"
 
  
