--- 

- hosts: all
  tasks:

  - name: install HTTPD package
    yum:
      name: httpd
      state: absent
    when: ansible_distribution == "CentOS"
    
  - name: add PHP support for apache
    yum:
      name: php
      state: absent
    when: ansible_distribution == "CentOS"
  
  - name: install apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: add libapache2-mod-php for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"


