--- 

- hosts: all
  become: yes
  tasks:

  - name: install HTTPD package
    yum:
      name: httpd
      state: absent 
    when: ansible_distribution == "CentOS"
    
  - name: add PHP support for apache
    yum:
      name: php
      state: absent
    when: ansible_distribution == "CentOS"

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 
  
  - name: install tmux package
    apt:
      name: tmux
      state: latest
    when: ansible_distribution == "Ubuntu"


        
