---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    yum:
      update only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb in "Ubuntu"
    when: ansible_distribution =="Ubuntu"
    package:
     name:
        - mariadb-server
     state: present
     
    