---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ftp_server
  become: true
  tasks:

  - name: install mariadb in "Ubuntu"
    when: ansible_distribution =="Ubuntu"
    package:
     name:
        - mariadb-server
     state: present

  - name: install mariadb in "CentOS"
    when: ansible_distribution =="CentOS"
    package:
     name:
        - mariadb
     state: present
  
    