---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: ftp_server        # aur mariabd sirf ftp server me hi hoga 
  become: true
  tasks:

  - name: install mariadb in "Ubuntu"
    when: ansible_distribution =="Ubuntu"
    package:
     name:
        - mariadb-server
     state: latest

  - name: install mariadb in "CentOS"
    when: ansible_distribution =="CentOS"
    package:
     name:
        - mariadb
     state: latest

- hosts: db_servers        # abhi mene tmux sirf db_server me install krna chahta hoon toh sirf usme hi hoga 
  become: true
  tasks:

  - name: install mariadb in "Ubuntu"
    when: ansible_distribution =="Ubuntu"
    package:
     name:
        - tmux
     state: latest

  - name: install mariadb in "CentOS"
    when: ansible_distribution =="CentOS"
    package:
     name:
        - tmux
     state: latest

  
    
